name = "ReactiveMP"
uuid = "a194aa59-28ba-4574-a09c-4a745416d6e3"
authors = ["Dmitry Bagaev <d.v.bagaev@tue.nl>", "Albert Podusenko <a.podusenko@tue.nl>", "Bart van Erp <b.v.erp@tue.nl>", "Ismail Senoz <i.senoz@tue.nl>"]
version = "5.2.1"

[deps]
BayesBase = "b4ee3484-f114-42fe-b91c-797d54a0c67e"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DomainIntegrals = "cc6bae93-f070-4015-88fd-838f9505a86c"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
ExponentialFamily = "62312e5e-252a-4322-ace9-a5f4bf9b357b"
FastCholesky = "2d5283b6-8564-42b6-bb00-83ed8e915756"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FixedArguments = "4130a065-6d82-41fe-881e-7a5c65156f7d"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MatrixCorrectionTools = "41f81499-25de-46de-b591-c3cfc21e9eaf"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PolyaGammaHybridSamplers = "c636ee4f-4591-4d8c-9fae-2dea21daa433"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Rocket = "df971d30-c9d6-4b37-b8ff-e965b2cb3a40"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
TinyHugeNumbers = "783c9a47-75a3-44ac-a16b-f1ab7b3acf04"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[weakdeps]
ExponentialFamilyProjection = "17f509fa-9a96-44ba-99b2-1c5f01f0931b"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[extensions]
ReactiveMPOptimisersExt = "Optimisers"
ReactiveMPProjectionExt = "ExponentialFamilyProjection"
ReactiveMPRequiresExt = "Requires"

[compat]
BayesBase = "1.5"
DataStructures = "0.17, 0.18"
DiffResults = "1.1.0"
Distributions = "0.24, 0.25"
DomainIntegrals = "0.3.2, 0.4"
DomainSets = "0.5.2, 0.6, 0.7"
ExponentialFamily = "2.0.0"
ExponentialFamilyProjection = "2.0.0"
FastCholesky = "1.3.0"
FastGaussQuadrature = "0.4, 0.5"
FixedArguments = "0.1"
ForwardDiff = "0.10"
HCubature = "1.0.0"
LazyArrays = "0.21, 0.22, 1, 2"
LinearAlgebra = "1.9"
LoopVectorization = "0.12"
MacroTools = "0.5"
MatrixCorrectionTools = "1.2.0"
Optim = "1.0.0"
Optimisers = "0.2, 0.3"
PolyaGammaHybridSamplers = "1.2.6"
PositiveFactorizations = "0.2"
Random = "1.9"
Requires = "1"
Rocket = "1.8.0"
SpecialFunctions = "2.3"
StaticArrays = "1.9.0"
StatsBase = "0.34.0"
StatsFuns = "1.3.0"
TinyHugeNumbers = "1.0.0"
TupleTools = "1.2.0"
Unrolled = "0.1.3"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ExponentialFamilyProjection = "17f509fa-9a96-44ba-99b2-1c5f01f0931b"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
Manopt = "0fc0a36d-df90-57f3-8f93-d78a9fc72bb5"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[targets]
test = ["Aqua", "Hwloc", "ReTestItems", "Test", "Pkg", "Logging", "InteractiveUtils", "TestSetExtensions", "Coverage", "Dates", "Distributed", "Documenter", "BenchmarkTools", "JET", "PkgBenchmark", "StableRNGs", "Optimisers", "DiffResults", "ExponentialFamilyProjection", "REPL", "Manopt"]
