blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions / Q&A (RxInfer)
    url: https://github.com/reactivebayes/RxInfer.jl/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“š Documentation
    url: https://reactivebayes.github.io/ReactiveMP.jl/stable/
    about: Check out our documentation for guides and API reference
  - name: ðŸŽ¯ Examples (RxInfer)
    url: https://examples.rxinfer.com
    about: Browse example models and use cases

